version: '3'
services:
  server:
    image: qnib/alplain-gocd-server
    ports:
     - 8153:8153
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - GOCD_SERVER_CLEAN_WORKSPACE=false
     - GO_SERVER_SYSTEM_PROPERTIES='-Dplugin.cd.go.contrib.elastic-agent.docker-swarm.log.level=debug'
